# Generated by Django 6.0 on 2026-01-14 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('default_coefficient', models.FloatField(default=1, help_text='Hệ số hao hụt mặc định')),
                ('warning_level_1', models.FloatField(default=0)),
                ('warning_level_2', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyLogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='daily_logs/')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailylog')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_done', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.dailylog')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLogMaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField()),
                ('daily_log_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='core.dailylogitem')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.project'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('completed_quantity', models.FloatField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.workitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('IN', 'Nhập'), ('OUT', 'Xuất')], max_length=3)),
                ('date', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workitem')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm_quantity', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('project', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_norms', to='core.project')),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workitem')),
            ],
        ),
        migrations.AddField(
            model_name='dailylogitem',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workitem'),
        ),
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_quantity', models.FloatField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailylog')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workitem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('project', 'log_date')},
        ),
        migrations.CreateModel(
            name='WorkItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.FloatField(help_text='Định mức cho 1 đơn vị công việc')),
                ('factor', models.FloatField(default=1)),
                ('quantity', models.FloatField(help_text='Số lượng dự trù')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.workitem')),
            ],
            options={
                'unique_together': {('work_item', 'material')},
            },
        ),
    ]
